### ISSUE TITLE
➕ [ADD] 네트워크 통신을 위한 세팅

### ISSUE THREAD

**Issue by jane1choi** [THE-SOPT-Joint-Seminar-ZEPETO/ZEPETO-iOS#14]
## 🦄 Feature Issue
서버통신을 위해 필요한 파일들을 추가합니다.

## 🦄 작업 브랜치
- network/#14-Setting

## 📝 To-do
- [x] Network 파일 폴더링
- [x] Alamofire 모듈화한 파일 추가
- [x] get, multipart-form data 통신을 위한 코드 추가
