### ISSUE TITLE
✨ [FEAT] Feed View UI 구성

### ISSUE THREAD

**Issue by jeongkite** [THE-SOPT-Joint-Seminar-ZEPETO/ZEPETO-iOS#4]
## 🦄 Feature Issue
Feed View UI를 구성합니다

## 🦄 작업 브랜치
- feature/#4-UI-feed

## 📝 To-do
- [x] 상단바 구성
- [x] 메인 이미지 배치
- [x] 오른쪽 하단 기능(프로필, 좋아요, 댓글, 공유) 영역 구성
- [x] 하단 콘텐츠 영역 구성
- [x] 콘텐츠 영역 메인 텍스트 더보기/숨기기 구현
